/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "hello/main.h"
/* Header for class com_example_httpserver_MainActivity */

#ifndef _Included_com_example_httpserver_MainActivity
#define _Included_com_example_httpserver_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_httpserver_MainActivity
 * Method:    startHttpServer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_p2plive_MainActivity_startHttpServer
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
